config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers do
      member do
        patch :set_best
      end
    end
  end

  root to: "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :question_id, :body, :user_id, presence: true

  def set_best
    ActiveRecord::Base.transaction do
      if question.best_answer
        question.best_answer.update!(best: false)
      end
      update!(best: true)
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, -> { order('best DESC') }, dependent: :destroy
  belongs_to :user

  validates :title, :body, :user_id, presence: true

  def best_answer
    answers.where(best: true).first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answers

  def author?(obj)
    id == obj.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :authenticate_user!
  before_action :load_question
  before_action :load_answer, except: [:create, :new, :set_best]
  before_action :check_authority, except: [:create, :new, :set_best]

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answers = @question.answers.all
    @answer.save
  end

  def edit
    @answers = @question.answers.all
  end

  def update
    @answer.update(answer_params)
  end

  def set_best
    @answer = @question.answers.find(params[:id])
    if current_user.author?(@question)
      @answer.set_best
    end
  end

  def destroy
    @answer.destroy
  end

  private
  def answer_params
    params.require(:answer).permit(:body)
  end

  def load_answer
    @answer = @question.answers.find(params[:id])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def check_authority
    redirect_to @question, notice: 'You are not thr author of answer.' unless current_user.author?(@answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :load_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answers = @question.answers
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to @question
      flash[:notice] = 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    if current_user.author?(@question) && @question.destroy
      flash[:notice] = 'Your question was successfully deleted.'
    else
      flash[:notice] = 'Your question was not deleted.'
    end
    redirect_to questions_path
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
.answer id="answer-#{answer.id}"
  p= answer.body
  - if answer.best?
    strong Best answer
  - elsif user_signed_in? && current_user.author?(@question)
    = link_to 'Set best', set_best_question_answer_path(@question, answer), method: :patch, remote: true

  - if answer.body && current_user && current_user.author?(answer)
    .btn-group
      = link_to 'Delete Answer', question_answer_path(answer.question_id, answer), method: :delete, remote: true, class: 'btn'
      = link_to 'Edit', '', class: 'edit-answer-link btn', data: { answer_id: answer.id }

    = form_for [@question, answer], remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
      .field
        = f.label :body, 'Edit answer'
        .answer-errors
        = f.text_area :body
      .actions
        = f.submit "save"

app/views/answers/_new.html.slim
= form_for [@question, @answer], remote: true do |f|
  - if @answer.errors.any?
    ul
      = @answer.errors.full_messages.each do |message|
        li = message
  .field
    = f.label :body, 'Answer'
    .answer-errors
    = f.text_area :body
  .actions
    = f.submit "Post answer"

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $('.answers').append('<%= j render @answer %>');
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%="#{@answer.id}"%>').hide('<%= j render @answer %>');

app/views/answers/new.html.slim
= form_for [@question, @answer] do |f|
  - if @answer.errors.any?
    ul
      = @answer.errors.full_messages.each do |message|
        li = message
  .field
    = f.label :body, 'Answer'
    br
    = f.text_area :body
  .actions
    = f.submit "Post answer"

app/views/answers/set_best.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $('#answer-<%="#{@answer.id}"%>').html('<%= j render @answer %>');
    $('.edit-answer-link').click(function(e) {
      var answer_id;
      e.preventDefault();
      $(this).hide();
      answer_id = $(this).data('answerId');
      return $('form#edit-answer-' + answer_id).show();
    });
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qna</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>.
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Registration', new_user_registration_path %> or <%= link_to 'sign in', new_user_session_path %>
  <% end %>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/questions/_question.html.slim
h1= @question.title
p= @question.body
- if current_user && current_user.author?(@question)
  .btn-group
    = link_to 'Delete question', @question, method: :delete, class: 'btn'
    = link_to 'Edit question', '', class: 'edit-question-link btn', data: { question: @question }

  = form_for [@question], remote: true, html: { id: "edit-question" } do |f|
    .field
      = f.label :title, 'Edit title'
      .answer-errors
      = f.text_area :title
    .field
      = f.label :body, 'Edit question'
      .answer-errors
      = f.text_area :body
    .actions
      = f.submit "save"

app/views/questions/index.html.slim
- @questions.each do |question|
  p= link_to question.title, question_path(question)
br
= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body, 'Text'
  = f.text_area :body
  = f.submit 'Create'

app/views/questions/show.html.slim
.question id="question"
  =render partial: 'question'
.answers
  =render @answers

- if current_user
  = render partial: 'answers/new'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
    <% @question.errors.full_messages.each do |message| %>
        $('.question-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $('#question').html('<%= j render @question %>');
<% end %>